Universe = vanilla 

+JobFlavour = "longlunch"
RequestCpus = 8
should_transfer_files = IF_NEEDED
executable = $(DIR)/Single_Photon/photon_14TeV_2026D60_HGCNose/condor_exec.sh
log        = $(DIR)/Single_Photon/photon_14TeV_2026D60_HGCNose/condor/$(ProcId)_output.log
max_retries = 3

notification = Always
notify_user = kyungseop.yoon@cern.ch

output = $(DIR)/Single_Photon/photon_14TeV_2026D60_HGCNose/condor/$(ProcId)_output.out
error = $(DIR)/Single_Photon/photon_14TeV_2026D60_HGCNose/condor/$(ProcId)_output.err
arguments = $(DIR)
queue 1
