Universe = vanilla 

+MaxRuntime = 20000
RequestCpus = 4
should_transfer_files = IF_NEEDED
executable = condor_exec.sh
log        = condor/$(ProcId)_output.log
max_retries = 3

notification = Always
notify_user = kyungseop.yoon@cern.ch

output = condor/$(ProcId)_output.out
error = condor/$(ProcId)_output.err

arguments = /afs/cern.ch/user/k/kyoon/CMSSW_12_0_0_pre4/src/HGCNose 50 3.5 1000 0 /eos/home-k/kyoon/CMSSW_12_0_0_pre4/electron_2026D60_HFNose
queue

arguments = /afs/cern.ch/user/k/kyoon/CMSSW_12_0_0_pre4/src/HGCNose 100 3.5 1000 0 /eos/home-k/kyoon/CMSSW_12_0_0_pre4/electron_2026D60_HFNose
queue

arguments = /afs/cern.ch/user/k/kyoon/CMSSW_12_0_0_pre4/src/HGCNose 150 3.5 1000 0 /eos/home-k/kyoon/CMSSW_12_0_0_pre4/electron_2026D60_HFNose
queue

arguments = /afs/cern.ch/user/k/kyoon/CMSSW_12_0_0_pre4/src/HGCNose 200 3.5 1000 0 /eos/home-k/kyoon/CMSSW_12_0_0_pre4/electron_2026D60_HFNose
queue

arguments = /afs/cern.ch/user/k/kyoon/CMSSW_12_0_0_pre4/src/HGCNose 250 3.5 1000 0 /eos/home-k/kyoon/CMSSW_12_0_0_pre4/electron_2026D60_HFNose
queue

arguments = /afs/cern.ch/user/k/kyoon/CMSSW_12_0_0_pre4/src/HGCNose 300 3.5 1000 0 /eos/home-k/kyoon/CMSSW_12_0_0_pre4/electron_2026D60_HFNose
queue
