Universe = vanilla 

+JobFlavour = "workday"
RequestCpus = 4
should_transfer_files = IF_NEEDED
executable = condor_exec.sh
log        = condor/$(ProcId)_output.log
max_retries = 3

notification = Always
notify_user = kyungseop.yoon@cern.ch

output = condor/$(ProcId)_output.out
error = condor/$(ProcId)_output.err

arguments = /afs/cern.ch/user/k/kyoon/CMSSW_11_3_0_pre5/src/HGCNose 50 3.5 500 0 /eos/home-k/kyoon/TICL_11_3_0_pre5/electron_2026D60_SmartPropagatorRK
queue

arguments = /afs/cern.ch/user/k/kyoon/CMSSW_11_3_0_pre5/src/HGCNose 150 3.5 500 0 /eos/home-k/kyoon/TICL_11_3_0_pre5/electron_2026D60_SmartPropagatorRK
queue

arguments = /afs/cern.ch/user/k/kyoon/CMSSW_11_3_0_pre5/src/HGCNose 300 3.5 500 0 /eos/home-k/kyoon/TICL_11_3_0_pre5/electron_2026D60_SmartPropagatorRK
queue
