Universe = vanilla 

+JobFlavour = "workday"
RequestCpus = 8
should_transfer_files = IF_NEEDED
executable = condor_exec.sh
log        = condor/$(ProcId)_output.log
max_retries = 3

notification = Always
notify_user = kyungseop.yoon@cern.ch

output = condor/$(ProcId)_output.out
error = condor/$(ProcId)_output.err
arguments = /afs/cern.ch/user/k/kyoon/CMSSW_11_3_0_pre1/src/HGCNose 50 3.5 500 0
queue

arguments = /afs/cern.ch/user/k/kyoon/CMSSW_11_3_0_pre1/src/HGCNose 200 3.5 500 0
queue
