Universe = vanilla 

+MaxRuntime = 20000
RequestCpus = 4
should_transfer_files = IF_NEEDED
executable = condor_exec.sh
log        = condor/$(ProcId)_output.log
max_retries = 3

notification = Always
notify_user = kyungseop.yoon@cern.ch

output = condor/$(ProcId)_output.out
error = condor/$(ProcId)_output.err

arguments = /afs/cern.ch/user/k/kyoon/CMSSW_12_0_0_pre4/src/HFNose 50 3.5 1000 0 /eos/home-k/kyoon/DATA_12_0_0_pre4/photon_2026D60_HFNose pset4
queue

arguments = /afs/cern.ch/user/k/kyoon/CMSSW_12_0_0_pre4/src/HFNose 100 3.5 1000 0 /eos/home-k/kyoon/DATA_12_0_0_pre4/photon_2026D60_HFNose pset4
queue

arguments = /afs/cern.ch/user/k/kyoon/CMSSW_12_0_0_pre4/src/HFNose 150 3.5 1000 0 /eos/home-k/kyoon/DATA_12_0_0_pre4/photon_2026D60_HFNose pset4
queue

arguments = /afs/cern.ch/user/k/kyoon/CMSSW_12_0_0_pre4/src/HFNose 200 3.5 1000 0 /eos/home-k/kyoon/DATA_12_0_0_pre4/photon_2026D60_HFNose pset4
queue

arguments = /afs/cern.ch/user/k/kyoon/CMSSW_12_0_0_pre4/src/HFNose 250 3.5 1000 0 /eos/home-k/kyoon/DATA_12_0_0_pre4/photon_2026D60_HFNose pset4
queue

arguments = /afs/cern.ch/user/k/kyoon/CMSSW_12_0_0_pre4/src/HFNose 300 3.5 1000 0 /eos/home-k/kyoon/DATA_12_0_0_pre4/photon_2026D60_HFNose pset4
queue
